### ISSUE TITLE
Package/module structure

### ISSUE THREAD

**Issue by drbild** [xaptum/xaptum-tpm-python#4]
Let's place this in `xaptum.tpm` rather than `xaptumtpm`. I'd like to standardize on having all of Xaptum's public code in sub-package of or modules in the `xaptum` package.

In order for multiple projects to share the `xaptum` package (e.g., both `pip install xaptum-tpm-python` and `pip install xaptum-client-python` try to install a `xaptum` package), each `xaptum/__init__.py`  just needs to have the following line.  Which you already do.

```python
__path__ = __import__('pkgutil').extend_path(__path__, __name__)
```

**Comment by zanebeckwith** [comment]
Gotcha.

Is PR #6 what you're looking for?

**Comment by drbild** [comment]
Exactly.
